
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Thrift server config
@camelName@ThriftServer:
  port: 3000
  name: @name@-thrift-server

# Eureka server
eureka:
  instance:
    appname: ${@camelName@ThriftServer.name}
    nonSecurePort: ${@camelName@ThriftServer.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
